theme: jekyll-theme-minimal
title: Your Code Displays Japanese Wrong
description: A static site to link people to when their code is displaying Japanese wrong.
# Analytics
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-ZRY737571F"
    anonymize_ip         : false
